// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
//
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
// /// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUzOtd1N4PrpqQbRY9r8D508H3okdgHkc',
    //appId: '1:914924731234:web:7df9ae44dfea398e764a3b',
    messagingSenderId: '914924731234',
    projectId: 'connectify-d3ce8',
    authDomain: 'connectify-d3ce8.firebaseapp.com',
    storageBucket: 'connectify-d3ce8.appspot.com',
      databaseURL: "https://connectify-d3ce8-default-rtdb.firebaseio.com",
      appId: "1:914924731234:web:b7aa3939c548d398764a3b"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKZwCF8-1niQp_YLZxRNmD50PcsjAYxu4',
    appId: '1:914924731234:android:fd940de5e75b02b5764a3b',
    messagingSenderId: '914924731234',
    projectId: 'connectify-d3ce8',
    storageBucket: 'connectify-d3ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQvHWV2gafHEa8roGwnVsHVnIF_8G8Oro',
    appId: '1:914924731234:ios:c1057d95c2d2bf38764a3b',
    messagingSenderId: '914924731234',
    projectId: 'connectify-d3ce8',
    storageBucket: 'connectify-d3ce8.appspot.com',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQvHWV2gafHEa8roGwnVsHVnIF_8G8Oro',
    appId: '1:914924731234:ios:c1057d95c2d2bf38764a3b',
    messagingSenderId: '914924731234',
    projectId: 'connectify-d3ce8',
    storageBucket: 'connectify-d3ce8.appspot.com',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUzOtd1N4PrpqQbRY9r8D508H3okdgHkc',
    appId: '1:914924731234:web:b7aa3939c548d398764a3b',
    messagingSenderId: '914924731234',
    projectId: 'connectify-d3ce8',
    authDomain: 'connectify-d3ce8.firebaseapp.com',
    storageBucket: 'connectify-d3ce8.appspot.com',
  );
}
